name: Build PDF

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update -y
          apt install -y pandoc
      - name: Build
        run: pandoc -s -o DRAFT.pdf DRAFT.md
      - name:
        uses: actions/upload-artifact@v4
        with:
          name: contracts-do-not-belong-in-the-language
          path: DRAFT.pdf


